language: php

sudo: false

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

env:
 global:
  - IGNORE_PATHS=sdk/,pix/,vendor/
  - IGNORE_NAMES=jquery*,styles.css,autoload_static.php
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE

matrix:
  exclude:
  - env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    php: 7.1
  - env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    php: 7.1
  - env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    php: 7.2
  - env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    php: 7.2

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci validate
#  - moodle-plugin-ci phpunit